apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxdemo
  labels:
    app: fluxdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fluxdemo
  template:
    metadata:
      labels:
        app: fluxdemo
    spec:
      containers:
        - name: fluxdemo
          image: subbuganapathy/fluxrepo
          ports:
              - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fluxdemo
  labels:
    app: fluxdemo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fluxdemo